FROM node:14-alpine

WORKDIR /app

ENTRYPOINT [ "npm" ]

# docker build -t mynpm .
# docker run -it -v "/path/in/your/machine:/app" mynpm init
# docker run -it -v "/path/in/your/machine:/app" mynpm install express --save
